#include "Sunday.h"
#include "UiText.h"

static const UI_TEXT_ENTRY gstUiTextTable[] =
    {
    {IDM_ABOUT, ORR_UI_LABEL_ABOUT},
    {IDM_EXIT, ORR_UI_LABEL_EXIT},
    {IDM_OPEN_HISTORY, ORR_UI_LABEL_OPEN_HISTORY},
    {IDM_OPEN_HIS_CLEAR, ORR_UI_LABEL_OPEN_HIS_CLEAR},
    {IDM_TRACE_MODE_ON, ORR_UI_LABEL_TRACE_MODE_ON},
    {IDM_TRC_VIEWTOGGLE, ORR_UI_LABEL_TRC_VIEWTOGGLE},
    {IDM_HEADHALF_EXCHANGE, ORR_UI_LABEL_HEADHALF_EXCHANGE},
    {IDM_COLOUR_EDIT_OPEN, ORR_UI_LABEL_COLOUR_EDIT_OPEN},
    {IDM_UNICODE_TOGGLE, ORR_UI_LABEL_UNICODE_TOGGLE},
    {IDM_NEWFILE, ORR_UI_LABEL_NEWFILE},
    {IDM_OPEN, ORR_UI_LABEL_OPEN},
    {IDM_OVERWRITESAVE, ORR_UI_LABEL_OVERWRITESAVE},
    {IDM_RENAMESAVE, ORR_UI_LABEL_RENAMESAVE},
    {IDM_FILE_CLOSE, ORR_UI_LABEL_FILE_CLOSE},
    {IDM_WINDOW_CHG_RVRS, ORR_UI_LABEL_WINDOW_CHG_RVRS},
    {IDM_WINDOW_CHANGE, ORR_UI_LABEL_WINDOW_CHANGE},
    {IDM_GENERAL_OPTION, ORR_UI_LABEL_GENERAL_OPTION},
    {IDM_CUT, ORR_UI_LABEL_CUT},
    {IDM_COPY, ORR_UI_LABEL_COPY},
    {IDM_PASTE, ORR_UI_LABEL_PASTE},
    {IDM_DELETE, ORR_UI_LABEL_DELETE},
    {IDM_SQSELECT, ORR_UI_LABEL_SQSELECT},
    {IDM_ALLSEL, ORR_UI_LABEL_ALLSEL},
    {IDM_LAYERBOX, ORR_UI_LABEL_LAYERBOX},
    {IDM_SJISCOPY_ALL, ORR_UI_LABEL_SJISCOPY_ALL},
    {IDM_RIGHT_GUIDE_SET, ORR_UI_LABEL_RIGHT_GUIDE_SET},
    {IDM_INS_TOPSPACE, ORR_UI_LABEL_INS_TOPSPACE},
    {IDM_DEL_LASTSPACE, ORR_UI_LABEL_DEL_LASTSPACE},
    {IDM_DEL_TOPSPACE, ORR_UI_LABEL_DEL_TOPSPACE},
    {IDM_DEL_LASTLETTER, ORR_UI_LABEL_DEL_LASTLETTER},
    {IDM_INCREMENT_DOT, ORR_UI_LABEL_INCREMENT_DOT},
    {IDM_DECREMENT_DOT, ORR_UI_LABEL_DECREMENT_DOT},
    {IDM_TOPMOST_TOGGLE, ORR_UI_LABEL_TOPMOST_TOGGLE},
    {IDM_DOTDIFF_LOCK, ORR_UI_LABEL_DOTDIFF_LOCK},
    {IDM_DOTDIFF_ADJT, ORR_UI_LABEL_DOTDIFF_ADJT},
    {IDM_PAGE_PREV, ORR_UI_LABEL_PAGE_PREV},
    {IDM_PAGE_NEXT, ORR_UI_LABEL_PAGE_NEXT},
    {IDM_UNDO, ORR_UI_LABEL_UNDO},
    {IDM_REDO, ORR_UI_LABEL_REDO},
    {IDM_SPACE_VIEW_TOGGLE, ORR_UI_LABEL_SPACE_VIEW_TOGGLE},
    {IDM_FILL_SPACE, ORR_UI_LABEL_FILL_SPACE},
    {IDM_EXTRACTION_MODE, ORR_UI_LABEL_EXTRACTION_MODE},
    {IDM_GRID_VIEW_TOGGLE, ORR_UI_LABEL_GRID_VIEW_TOGGLE},
    {IDM_RIGHT_RULER_TOGGLE, ORR_UI_LABEL_RIGHT_RULER_TOGGLE},
    {IDM_FILE_PREV, ORR_UI_LABEL_FILE_PREV},
    {IDM_FILE_NEXT, ORR_UI_LABEL_FILE_NEXT},
    {IDM_INCR_DOT_LINES, ORR_UI_LABEL_INCR_DOT_LINES},
    {IDM_DECR_DOT_LINES, ORR_UI_LABEL_DECR_DOT_LINES},
    {IDM_UNDER_RULER_TOGGLE, ORR_UI_LABEL_UNDER_RULER_TOGGLE},
    {IDM_IMAGE_SAVE, ORR_UI_LABEL_IMAGE_SAVE},
    {IDM_TMPLT_GROUP_PREV, ORR_UI_LABEL_TMPLT_GROUP_PREV},
    {IDM_TMPLT_GROUP_NEXT, ORR_UI_LABEL_TMPLT_GROUP_NEXT},
    {IDM_MENUEDIT_DLG_OPEN, ORR_UI_LABEL_MENUEDIT_DLG_OPEN},
    {IDM_ACCELKEY_EDIT_DLG_OPEN, ORR_UI_LABEL_ACCELKEY_EDIT_DLG_OPEN},
    {IDM_SQUARE_PASTE, ORR_UI_LABEL_SQUARE_PASTE},
    {IDM_REBER_DORESET, ORR_UI_LABEL_REBER_DORESET},
    {IDM_FIND_DLG_OPEN, ORR_UI_LABEL_FIND_DLG_OPEN},
    {IDM_FIND_HIGHLIGHT_OFF, ORR_UI_LABEL_FIND_HIGHLIGHT_OFF},
    {IDM_FIND_JUMP_NEXT, ORR_UI_LABEL_FIND_JUMP_NEXT},
    {IDM_FIND_JUMP_PREV, ORR_UI_LABEL_FIND_JUMP_PREV},
    {IDM_FIND_TARGET_SET, ORR_UI_LABEL_FIND_TARGET_SET},
    {IDM_DOT_SPLIT_RIGHT, ORR_UI_LABEL_DOT_SPLIT_RIGHT},
    {IDM_DOT_SPLIT_LEFT, ORR_UI_LABEL_DOT_SPLIT_LEFT},
    {IDM_POSITION_RESET, ORR_UI_LABEL_POSITION_RESET},
    {IDM_PAGEL_RETURN_FOCUS, ORR_UI_LABEL_PAGEL_RETURN_FOCUS},
    {IDM_PAGEL_ADD, ORR_UI_LABEL_PAGEL_ADD},
    {IDM_PAGEL_INSERT, ORR_UI_LABEL_PAGEL_INSERT},
    {IDM_PAGEL_DELETE, ORR_UI_LABEL_PAGEL_DELETE},
    {IDM_PAGEL_UPFLOW, ORR_UI_LABEL_PAGEL_UPFLOW},
    {IDM_PAGEL_DOWNSINK, ORR_UI_LABEL_PAGEL_DOWNSINK},
    {IDM_PAGEL_DUPLICATE, ORR_UI_LABEL_PAGEL_DUPLICATE},
    {IDM_PAGEL_RENAME, ORR_UI_LABEL_PAGEL_RENAME},
    {IDM_PAGEL_AATIP_TOGGLE, ORR_UI_LABEL_PAGEL_AATIP_TOGGLE},
    {IDM_MN_INSFRAME_SEL, ORR_UI_LABEL_MN_INSFRAME_SEL},
    {IDM_MN_USER_REFS, ORR_UI_LABEL_MN_USER_REFS},
    {IDM_BRUSH_ON_OFF, ORR_UI_LABEL_BRUSH_ON_OFF},
    {IDM_BRUSH_PALETTE, ORR_UI_LABEL_BRUSH_PALETTE},
    {IDM_MN_UNISPACE, ORR_UI_LABEL_MN_UNISPACE},
    {IDM_INSERT_PALETTE, ORR_UI_LABEL_INSERT_PALETTE},
    {IDM_IN_UNI_SPACE, ORR_UI_LABEL_IN_UNI_SPACE},
    {IDM_IN_01SPACE, ORR_UI_LABEL_IN_01SPACE},
    {IDM_IN_02SPACE, ORR_UI_LABEL_IN_02SPACE},
    {IDM_IN_03SPACE, ORR_UI_LABEL_IN_03SPACE},
    {IDM_IN_04SPACE, ORR_UI_LABEL_IN_04SPACE},
    {IDM_IN_05SPACE, ORR_UI_LABEL_IN_05SPACE},
    {IDM_IN_08SPACE, ORR_UI_LABEL_IN_08SPACE},
    {IDM_IN_10SPACE, ORR_UI_LABEL_IN_10SPACE},
    {IDM_IN_16SPACE, ORR_UI_LABEL_IN_16SPACE},
    {IDM_INSTAG_COLOUR, ORR_UI_LABEL_INSTAG_COLOUR},
    {IDM_INSTAG_SPO, ORR_UI_LABEL_INSTAG_SPO},
    {IDM_INSTAG_GRADIENT, ORR_UI_LABEL_INSTAG_GRADIENT},
    {IDM_INSFRAME_EDIT, ORR_UI_LABEL_INSFRAME_EDIT},
    {IDM_PAGELIST_VIEW, ORR_UI_LABEL_PAGELIST_VIEW},
    {IDM_ON_PREVIEW, ORR_UI_LABEL_ON_PREVIEW},
    {IDM_FILL_ZENSP, ORR_UI_LABEL_FILL_ZENSP},
    {IDM_FRMINSBOX_QCLOSE, ORR_UI_LABEL_FRMINSBOX_QCLOSE},
    {IDM_FRAME_INS_DECIDE, ORR_UI_LABEL_FRAME_INS_DECIDE},
    {IDM_FRMINSBOX_OPEN, ORR_UI_LABEL_FRMINSBOX_OPEN},
    {IDM_FRMINSBOX_PADDING, ORR_UI_LABEL_FRMINSBOX_PADDING},
    {IDM_USERINS_NA, ORR_UI_LABEL_USERINS_NA},
    {IDM_LYB_INSERT, ORR_UI_LABEL_LYB_INSERT},
    {IDM_LYB_OVERRIDE, ORR_UI_LABEL_LYB_OVERRIDE},
    {IDM_LYB_DO_EDIT, ORR_UI_LABEL_LYB_DO_EDIT},
    {IDM_LYB_COPY, ORR_UI_LABEL_LYB_COPY},
    {IDM_LYB_DELETE, ORR_UI_LABEL_LYB_DELETE},
    {IDM_NOW_PAGE_REFRESH, ORR_UI_LABEL_NOW_PAGE_REFRESH},
    {IDM_MIRROR_INVERSE, ORR_UI_LABEL_MIRROR_INVERSE},
    {IDM_UPSET_INVERSE, ORR_UI_LABEL_UPSET_INVERSE},
};

static const INT giUiTextCount = static_cast<INT>(sizeof(gstUiTextTable) / sizeof(gstUiTextTable[0]));

const UI_TEXT_ENTRY *UiTextFindEntry(UINT dCommandID)
{
    INT lo = 0, hi = giUiTextCount - 1;
    while (lo <= hi)
    {
        INT mid = lo + (hi - lo) / 2;
        UINT midID = gstUiTextTable[mid].dCommandID;
        if (midID == dCommandID)
            return &gstUiTextTable[mid];
        if (midID < dCommandID)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return nullptr;
}

LPCTSTR UiTextGetLabel(UINT dCommandID)
{
    const UI_TEXT_ENTRY *p = UiTextFindEntry(dCommandID);
    return p ? p->ptLabel : nullptr;
}

LPCTSTR UiTextGetMenuText(UINT dCommandID)
{
    return UiTextGetLabel(dCommandID);
}